export const ONETOTAL = "ONETOTAL";
export const ALIPAYNAME = "ALIPAYNAME";
export const INIT_DEORDER_LIST = "INIT_DEORDER_LIST";
export const LOCKNUM = "LOCKNUM";
export const INIT_DEORDER_LISTTOTAL = "INIT_DEORDER_LISTTOTAL";
export const INIT_PARKINGLOT_LIST = "INIT_PARKINGLOT_LIST";
export const ONEFANMLI = "ONEFANMLI";